#ifndef CONSTANTS_HLSL
#define CONSTANTS_HLSL

#define CBUFFER_SLOT_TRANSFORM 0
#define CBUFFER_SLOT_PIXEL 1
#define CBUFFER_REGISTER_TRANSFORM b0
#define CBUFFER_REGISTER_PIXEL b1

#define SAMPLER_SLOT_GBUFFER 0
#define SAMPLER_SLOT_DEPTH 1
#define SAMPLER_REGISTER_GBUFFER s0
#define SAMPLER_REGISTER_DEPTH s1

#define TEXTURE_SLOT_POSITION 0
#define TEXTURE_SLOT_DIFFUSE 1
#define TEXTURE_SLOT_NORMAL 2
#define TEXTURE_SLOT_DEPTH 3
#define TEXTURE_REGISTER_POSITION t0
#define TEXTURE_REGISTER_DIFFUSE t1
#define TEXTURE_REGISTER_NORMAL t2
#define TEXTURE_REGISTER_DEPTH t3

#endif