#ifndef CONSTANTS_HLSL
#define CONSTANTS_HLSL

// TODO: refactor this into a more efficient system

#define CBUFFER_SLOT_VERTEX 0
#define CBUFFER_SLOT_PIXEL 1
#define CBUFFER_SLOT_COMPUTE 2
#define CBUFFER_REGISTER_VERTEX b # CBUFFER_SLOT_VERTEX
#define CBUFFER_REGISTER_PIXEL b # CBUFFER_SLOT_PIXEL
#define CBUFFER_REGISTER_COMPUTE b # CBUFFER_SLOT_COMPUTE

#define SAMPLER_SLOT_ANISOTROPIC 0
#define SAMPLER_SLOT_POINT 1
#define SAMPLER_SLOT_POINT_COMPARE 2
#define SAMPLER_REGISTER_ANISOTROPIC s # SAMPLER_SLOT_ANISOTROPIC
#define SAMPLER_REGISTER_POINT s # SAMPLER_REGISTER_POINT
#define SAMPLER_REGISTER_POINT_COMPARE s # SAMPLER_SLOT_POINT_COMPARE

#define TEXTURE_SLOT_DIFFUSE 0
#define TEXTURE_SLOT_NORMAL 1
#define TEXTURE_SLOT_DEPTH 2
#define TEXTURE_SLOT_EXTRA 3
#define TEXTURE_REGISTER_DIFFUSE t # TEXTURE_SLOT_DIFFUSE
#define TEXTURE_REGISTER_NORMAL t # TEXTURE_SLOT_NORMAL
#define TEXTURE_REGISTER_DEPTH t # TEXTURE_SLOT_DEPTH
#define TEXTURE_REGISTER_EXTRA t # TEXTURE_SLOT_EXTRA

#define SBUFFER_SLOT_BONE_TRANSFORMS 0
#define SBUFFER_REGISTER_BONE_TRANSFORMS c # SBUFFER_SLOT_BONE_TRANSFORMS

#define UAV_SLOT 0
#define UAV_REGISTER u # UAV_SLOT

#define SDSM_THREAD_GROUP_SIZE 16
#define SDSM_NUM_THREADS (SDSM_THREAD_GROUP_SIZE * SDSM_THREAD_GROUP_SIZE)

#define NUM_BONES_PER_VERTEX 4

#endif